# Generated by Django 4.0.1 on 2022-01-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkemail',
            name='csvFile',
        ),
    ]
